Repository afids/afids-validator, pull requests merged in 2021-11, with the labels that each got.

#156 MAINT: Split actions workflow between CI and Release
  .github/workflows/afids-validator_ci.yml
  .github/workflows/afids-validator_release.yml
  .gitignore
  README.md
Labels: maintenance

#158 MAINT: Update heroku action name
  .github/workflows/afids-validator_ci.yml
  .github/workflows/afids-validator_release.yml
Labels: bug

#159 BUG: Add test dependency for checkout
  .github/workflows/afids-validator_ci.yml
Labels: bug

#160 BUG: rm test dependency, add checkout of master
  .github/workflows/afids-validator_ci.yml
Labels: bug

#154 ENH: OAuth login with ORCID
  .env.template
  README.md
  afidsvalidator/__init__.py
  afidsvalidator/model.py
  afidsvalidator/orcid.py
  afidsvalidator/static/images/ORCIDiD_iconvector.svg
  afidsvalidator/static/images/under-construction-gif-11.gif
  afidsvalidator/templates/base.html
  afidsvalidator/templates/login.html
  afidsvalidator/views.py
  config.py
  manage.py
  migrations/versions/56d89145adbb_.py
  migrations/versions/7b4e00130929_.py
  migrations/versions/a0928ce2eee6_.py
  setup.py
Labels: enhancement

#161 Make draft log dependent on test instead of lint
  .github/workflows/afids-validator_ci.yml
Labels: bug

#162 BUG: Fix prod deploy
  .github/workflows/afids-validator_release.yml
Labels: bug

#163 Use env variables to find tag
  .github/workflows/afids-validator_release.yml
Labels: bug

#165 BUG: Release patch fix
  .github/workflows/afids-validator_ci.yml
  .github/workflows/afids-validator_release.yml
  README.md
Labels: bug
