Repository afids/afids-validator, pull requests merged in 2022-10, with the labels that each got.

#155 MAINT: Setup poetry
  .github/workflows/afids-validator_ci.yml
  .gitignore
  README.md
  afidsvalidator/templates/app.html
  afidsvalidator/templates/base.html
  afidsvalidator/views.py
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
Labels: skip_changelog

#181 Pre-commit and poetry tasks
  .pre-commit-config.yaml
  README.md
  afidsvalidator/__init__.py
  afidsvalidator/model.py
  afidsvalidator/orcid.py
  afidsvalidator/views.py
  afidsvalidator/visualizations.py
  pyproject.toml
Labels: enhancement

#183 Fix quality
  .github/ISSUE_TEMPLATE.md
  .github/workflows/afids-validator_ci.yml
  .gitignore
  .pre-commit-config.yaml
  afidsvalidator/__init__.py
  afidsvalidator/model.py
  afidsvalidator/orcid.py
  afidsvalidator/static/images/ORCIDiD_iconvector.svg
  afidsvalidator/templates/contact.html
  afidsvalidator/templates/db.html
  afidsvalidator/templates/login.html
  afidsvalidator/views.py
  afidsvalidator/visualizations.py
  config.py
  manage.py
  poetry.lock
  pyproject.toml
  test/__init__.py
  test/resources/incorrect_desc.json
  test/resources/infinite_coord.json
  test/resources/invalid_content.fcsv
  test/resources/invalid_content.json
  test/resources/invalid_content_valid_header.fcsv
  test/resources/missing_row_10.json
  test/resources/too_few_rows.json
  test/resources/too_many_rows.json
  test/resources/valid.json
  test/resources/valid_flip.json
  test/resources/valid_misordered.json
  test/resources/valid_nhp.fcsv
  test/resources/valid_nhp.json
  test/test_model.py
  test/test_templates.py
Labels: maintenance

#184 Refactor app.html
  afidsvalidator/model.py
  afidsvalidator/templates/app.html
  afidsvalidator/views.py
  config.py
Labels: maintenance
