Repository afids/afids-validator, pull requests merged in 2023-02, with the labels that each got.

#190 Set up non-heroku deploy workflow
  .github/workflows/afids-validator_ci.yml
  .github/workflows/afids-validator_release.yml
  .github/workflows/deploy.yml
  afidsvalidator.ini
  afidsvalidator/config.py
  afidsvalidator/wsgi.py
  fabrictasks.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#193 Install deploy extra
  fabrictasks.py
Labels: bug

#194 Overwrite current symlink for deploy
  fabrictasks.py
Labels: bug

#196 Update version updater
  .github/workflows/afids-validator_release.yml
Labels: bug

#195 Don't dereference current for symlinks
  fabrictasks.py
Labels: bug

#197 Use push-protected for releases
  .github/workflows/afids-validator_release.yml
Labels: bug

#199 Update dependencies and enforce werkzeug > 2.2.2
  afidsvalidator/visualizations.py
  poetry.lock
  pyproject.toml
Labels: dependencies
